name: LongUIS
version: @version@
main: cafe.qwq.longuis.LongUIS
api-version: 1.13
authors: [hookan]
commands:
  luiopengui:
    description: Open a LongUI GUI at client.
    permission: lui.use
    aliases: [luiopen,lopen]
permissions:
  lui.use:
    description: The permission used to open a GUI for a player.
    default: op
